FROM python:3.12-rc-alpine

WORKDIR /app

COPY ./requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY ./src ./src

EXPOSE 8080

WORKDIR /app/src

CMD ["flask", "--app", "main", "--debug", "run", "--host", "0.0.0.0", "--port", "8080"]
